### ISSUE TITLE
RECAP iconbutton mysteriously disappeared (no repro case)

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#202] opened 2017-11-15 13:22 UTC
After upgrading from 0.9.9.2 to 1.1.7 in FF56 (with various RECAP versions along the way) and having it function fine, my kernel paniced overnight for unrelated reasons.

Upon return, the iconbutton was missing from the status bar in Firefox, and not available as an option in Customize.

I tried clearing out all preferences to no avail.
I tried manually removing references in `prefs.js`, `extensions.js`, `xulstore.js`.
I uninstalled RECAP, and reinstalled.
I uninstalled, manually removed refenreces, and reinstalled.
Still no change.

And then the extension was not working at all. (before it was working with the iconbutton missing—or so I believed).

Then I reinstalled 0.9.9.2. Which worked fine.

Then I upgraded to 1.1.7. stdout or stderr from the firefox process spewed 96 of these:

```
Extension error: TypeError: items.options is undefined moz-extension://0aca09aa-5baf-6545-88c1-9246114796ab/toolbar_button.js 48
[[Exception stack
updateToolbarButton/<@moz-extension://0aca09aa-5baf-6545-88c1-9246114796ab/toolbar_button.js:48:1
Current stack
runSafeSyncWithoutClone@resource://gre/modules/ExtensionUtils.jsm:63:129
runSafeSync@resource://gre/modules/ExtensionUtils.jsm:94:37
runSafe@resource://gre/modules/ExtensionCommon.jsm:164:32
wrapPromise/<@resource://gre/modules/ExtensionCommon.jsm:353:13
]]
```

So I launched the debugger from `about:debugging` and of course the problem went away.
And then the extension worked.

Restarting firefox, the extension continues to work, and the log spew is gone.

I have no explanation for what went on, and I suspect something in the above narrative is incorrect. No idea what it is.

Filing this so that if someone else sees this, or a similar problem, we can correlate.

**Comment by johnhawkinson** [comment] 2017-11-15 13:33
Does not reproduce kill -9'ing Firefox or other similar measures. No clue.

**Comment by mlissner** [comment] 2017-11-15 17:06
Yeah, we don't control whether the icon shows — that's at the browser level. I suggest closing, but I appreciate getting/seeing the notes in case it happens to somebody else.

**Comment by johnhawkinson** [comment] 2017-11-15 17:09
well, at a minimum we should guard the options['items'] dereference

**Comment by mlissner** [comment] 2017-11-15 18:26
That's a FF 56 issue caused by the defaults not yet being set. It'll go away in 57, where the onInstall listener actually works.

**Comment by johnhawkinson** [comment] 2017-11-16 00:44
Regardless. Please merge https://github.com/freelawproject/recap-chrome/pull/30 to fix it.
It's not one random message, it's hundreds of lines of spew.

**Comment by mlissner** [comment] 2017-11-16 00:48
Merged! All set here (for now?)

**Comment by johnhawkinson** [comment] 2017-11-16 00:54
*shrug* I'd like to know if other people are seeing this, but I tend to hang on to open issues for a long time, not just hours.

**Comment by mlissner** [comment] 2017-11-16 05:03
I try to only keep 'em open if they're active, and reopen liberally if things reignite. If there's no work or solution or discussion on an issue...it goes out of the limelight. They're easy enough to reopen.

**Closed as completed by mlissner** 2017-11-16 05:03 UTC
