### ISSUE TITLE
recap-chrome regresses external PDF viewer support.

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#183] opened 2017-11-07 22:44 UTC
The classic Firefox extension prefers downloading to an external PDF viewer over internal browser viewing, and makes this clear in the options dialog:

<img width="641" alt="screen shot 2017-11-07 at 17 41 13" src="https://user-images.githubusercontent.com/1270718/32521814-f7b1af26-c3e2-11e7-908b-c6a26eed9828.png">

At present, recap-chrome requires you to take action you to save the file when configured for in-browser viewing, and fails to perform proper file renaming when configured for external browser viewing.

This is a regression.

On the other hand, this is 2017 and people who prefer in-browser PDF viewing are just wrong, not insane, and they need to be accomodated. So the extension needs to handle all of these things.

Also, external viewing and automatic downloading are preferred from a UI sfficiency point of view. The user should not have to click an extra button to save the document to disk (esp. a document they paid for!).

**Comment by mlissner** [comment] 2017-11-10 01:14
Well, this indicates that it's not possible to get the file name right on external PDF viewers when used with iframes (as we do): https://stackoverflow.com/questions/40507464/how-can-i-set-the-filename-for-base64-pdf-in-iframe.

I'll keep hunting.

**Comment by johnhawkinson** [comment] 2017-11-10 01:17
Yeah, that's the sense I had preliminarily from looking at this, although I haven't done a complete evaluation.

The obvious answer is to not use an `<iframe>` when the external saving preference is set.

**Comment by mlissner** [comment] 2017-11-10 01:37
Hm. I must not know what to look for. I can't find any way to take a blob and just return it as a PDF. All the solutions I'm finding involve using an `iframe` or an `<embed>`.

**Comment by johnhawkinson** [comment] 2017-11-10 01:46
https://www.google.com/search?num=100&q=js+save+blob+to+filename&oq=js+save+blob+to+filename

offers 2 examples of similar solutions:
https://stackoverflow.com/questions/23451726/saving-binary-data-as-file-using-javascript-from-a-browser
https://stackoverflow.com/questions/19327749/javascript-blob-filename-without-link

**Comment by mlissner** [comment] 2017-11-10 05:19
I like it. Creating a hidden anchor link, and then clicking it seems to be the magic incantation. I'll get this sorted tomorrow.

**Comment by mlissner** [comment] 2017-11-10 07:58
With #175 done, this will make more sense. Else we wouldn't have known which of the PDF files names to serve up.

**Comment by mlissner** [comment] 2017-11-10 20:37
Hm. It turns out that there's no way to access the user's preferences, so no way to know if they prefer the in-browser PDF reader or not. There might not be a good way to fix this aside from providing a weird setting that says, "I use an external PDF viewer."

**Comment by mlissner** [comment] 2017-11-11 18:50
Somebody on the IRC channel says this might be doable by making a `File()` instance? I have no idea...it's yet another JS API I'm not familiar with.

**Comment by mlissner** [comment] 2017-11-11 23:11
I poked around with `File()` objects. Not much hope there. I'm asking one more time on Stackoverflow, but I think this is a "Can't fix": 

https://stackoverflow.com/questions/47243766/how-to-serve-blob-and-have-good-filename-for-all-users

The only solution that *might* work is to use PDF.js to distribute our own in-browser PDF reader, but that's a mighty big solution.

**Comment by johnhawkinson** [comment] 2017-11-11 23:12
I don't understand, what's the problem with the download/anchor sugestion, from above?

Anyhow, please don't close it as cantfix if you can't figure it out. I will take a stab at it next week.

**Comment by johnhawkinson** [comment] 2017-11-11 23:13
> There might not be a good way to fix this aside from providing a weird setting that says, "I use an external PDF viewer."

I thought it was clear this was a requirement. Hence the discussion in https://github.com/freelawproject/recap/issues/185#issuecomment-343538467

**Comment by mlissner** [comment] 2017-11-11 23:47
Well, I wanted to try a few things out and see if there was any hope. I guess we can just have a setting that says, "Show PDF previews" That'd be pretty clear for folks I think.

**Comment by johnhawkinson** [comment] 2017-11-11 23:49
There's something to be said for mimicing the recap-firefox UI here. Avoiding regression, you know...:

<img width="641" alt="screen shot 2017-11-02 at 14 21 54" src="https://user-images.githubusercontent.com/1270718/32522031-a467bfb2-c3e3-11e7-9fc9-b98c0a4c4437.png">

I don't think "Show PDF previews" is in any way clear. "Preview" doesn't to me imply in-browser or out-of-browser. "Prevents in-browser viewing" is clear. "Use external PDF viewer" is clear.  (And that's without considering potential confusion with Preview.app)

**Comment by mlissner** [comment] 2017-11-11 23:57
The "Preview" verbiage is what Firefox itself uses. Their options are:

 - Preview in Firefox
 - Always Ask
 - Save file

I'm fine with "Use external viewer for PDFs" though.

**Comment by johnhawkinson** [comment] 2017-11-11 23:58
Indeed. I would support departing from their nomenclature because…it's bad.

**Comment by mlissner** [comment] 2017-11-12 03:42
I missed this message earlier: 

> I don't understand, what's the problem with the download/anchor sugestion, from above?

The problem is that for people that prefer the in-browser viewer, that forces the item to download. 

> Anyhow, please don't close it as cantfix if you can't figure it out. I will take a stab at it next week.

Yeah, I'm not closing it. We need some kind of solution here.

Even once there's a setting for "Force external PDF viewer", that doesn't solve it, I don't think. If the browser is set to download, and the user has this option unchecked, we'll be right where we started: The external viewer will pop up for every download, and the filename will be no good.

**Comment by johnhawkinson** [comment] 2017-11-13 01:51
Another approach is to adjust what is interstitial on the download confirmation page, and do what SSRN does, offering the user a choice with two buttons, rather than PACER's single button:
<img width="1165" alt="screen shot 2017-11-12 at 20 49 21" src="https://user-images.githubusercontent.com/1270718/32706389-29788910-c7eb-11e7-8ed0-2b96b6434191.png">

I don't love this approach either.

**Comment by mlissner** [comment] 2017-11-13 17:54
Even this doesn't work unless we ship PDF.js. If you clicked the "Open in Browser" button and have Firefox set to use your external viewer, you'll still use your external viewer.

**Comment by johnhawkinson** [comment] 2017-11-16 00:50
So, have you started down this path, @milssner?
Do you have a branch you're working on? Should I pick this up?
I would like to see this implemented in hours-to-days, given that the upgrade happened.

At the risk of stating the obvious:
> The problem is that for people that prefer the in-browser viewer, that forces the item to download.

Yes, you only do that when external PDF downloading is enabled.
Maybe we could do better, but best is the enemy of good enough.

**Comment by mlissner** [comment] 2017-11-16 04:09
I haven't begun, no. There's no way to check Firefox settings from an
extension.

**Comment by mlissner** [comment] 2017-12-06 22:56
I'm going to attempt to get this version out to some testers today.

**Comment by mlissner** [comment] 2017-12-09 00:02
No comment from testers or nobody tested it. Not sure which. Going to try one more ping, and if that fails, it's feeling pretty good to me at least.

**Comment by mlissner** [comment] 2017-12-11 20:36
I haven't gotten much response in the way of testers, so I think we just have to declare this working. I haven't seen any errors with it, and I presume your silence is good news too. Closing for now, but let me know if there's a reason to reopen and I'll happily do so.

**Closed as completed by mlissner** 2017-12-11 20:36 UTC

**Comment by johnhawkinson** [comment] 2017-12-12 02:09
> and I presume your silence is good news too

Sorry, yes, I've been running with this code from my development tree for weeks since #32 was instantiated and it's been fine.
Although I do think it may be worth it's worth further thought to the SSRN approach in https://github.com/freelawproject/recap/issues/183#issuecomment-343788912 because I suspect it may be beneficial for more users than I realize.

I do not have a good model for user behavior/desire with respect to PDF-in-browser vs. download.

**Comment by mlissner** [comment] 2017-12-12 05:48
I like the SSRN model too, actually, but to have a "View in Browser" button, we'd have to ship PDF.js. Else folks like you would click the button and would still download the PDF. Shipping PDF.js probably isn't the end of the world (I think it's pretty stable these days), but it's pretty darned big. And this is more invasive than most things RECAP does.

**Comment by johnhawkinson** [comment] 2017-12-12 13:35
_Well_.

> I like the SSRN model too, actually,

I should be clear, I don't actually like it. Just I think there may be demand for it.

> but to have a "View in Browser" button, we'd have to ship PDF.js

I agree the extension shouldn't.

>Else folks like you would click the button and would still download the PDF.

Well...maybe that's OK? It's what seems to happen with SSRN, actually.

> Shipping PDF.js probably isn't the end of the world (I think it's pretty stable these days), but it's pretty darned big. And this is more invasive than most things RECAP does.

Well, this could be handled by the CL webserver using a different endpoint for the download. Of course, if that forces the client to download PDF.js from CL that seems like it should be even worse than bundling it in the extension, at least from a network efficiency standpoint, even though it doesn't feel as bad.
