### ISSUE TITLE
RECAP does not parse or preserve criminal charge information

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/recap#230] opened 2018-01-10 00:05 UTC
A significant part of the PACER docket metadata for criminal cases is the criminal charge information. It appears in the Parties section of the docket report. Although the RECAP client sends the entire docket report to the server, the juriscraper parser and the CourtListener server neither parse nor store nor display this information.

Note that this is not a regression -- the historical IA RECAP server did not handle this information either.
I thought about this recently when looking more closely at the parser in https://github.com/freelawproject/courtlistener/issues/754#issuecomment-356160196

For instance, in the case in question in that comment, https://www.courtlistener.com/docket/6254625/parties/united-states-v-benzadon-boutin/, the defendant's section of the docket report has this information:

<table width="100%" cellspacing="5" border="0"><tbody><tr><td width="40%" valign="top">Assigned to: Chief Judge Dora Lizette Irizarry</td></tr>

<tr>
<td valign="top"><br><b><u>Defendant                                 (1)</u></b></td>
</tr>

<tr>
<td width="40%" valign="top">
<b>Salomon Benzadon Boutin</b>
<br><i>TERMINATED: 01/03/2018</i>
</td>
<td width="20%" valign="top" align="right">represented&nbsp;by</td><td width="40%" valign="top"><b>Mia                  Eisner-Grynberg                                   </b>
<br>Federal Defenders of New York                               
<br>One Pierrepont Plaza                                        
<br>16th Floor                                                  
<br>Brooklyn, NY 11201          
<br>718-330-1257             
<br>Fax: 718-855-0760        
<br>Email: mia_eisner-grynberg@fd.org
<br><i>LEAD ATTORNEY</i>
<br><i>ATTORNEY TO BE NOTICED</i><br><br>
<b>Peter                Kirchheimer                                       </b>
<br>Federal Defenders of New York, Inc.                         
<br>One Pierrepont Plaza, 16th Floor                            
<br>Brooklyn, NY 11201          
<br>(718) 330-1200           
<br>Fax: (718) 855-0760      
<br>Email: Peter_Kirchheimer@fd.org
<br><i>TERMINATED: 12/11/2017</i>
<br><i>LEAD ATTORNEY</i>
<br><i>ATTORNEY TO BE NOTICED</i>
<br><i>Designation: Public Defender or Community Defender Appointment</i><br><br>
<b>S. Isaac             Wheeler                                           </b>
<br>Federal Defenders of New York, Inc.                         
<br>52 Duane Street, 10th Floor                                 
<br>New York, NY 10007          
<br>(212)417-8717            
<br>Fax: (212)571-0392       
<br>Email: isaac_wheeler@fd.org
<br><i>ATTORNEY TO BE NOTICED</i>
<br><i>Designation: Public Defender or Community Defender Appointment</i></td></tr>

<tr>
<td width="40%" valign="top"><br><b><u>Pending Counts</u></b></td>
<td></td>
<td width="40%" valign="top"><br><b><u>Disposition</u></b></td>
</tr>

<tr>
<td width="40%" valign="top">None</td>
</tr>

<tr>
<td width="40%" valign="top"><br><b><u>Highest Offense Level (Opening)</u></b></td>
</tr>
<tr>
<td width="40%" valign="top">None</td>
</tr>

<tr>
<td width="40%" valign="top"><br><b><u>Terminated Counts</u></b></td>
<td></td>
<td width="40%" valign="top"><br><b><u>Disposition</u></b></td>
</tr>

<tr>
<td width="40%"> Attempted Money Laundering- Title 18, United States Code, Sections 1956(a)(3)(B), 2 and 3551 et seg.)<br>(1)</td>
<td></td>
<td width="40%">Dismissed on deft's motion.</td>
</tr>

<tr>
<td width="40%"> Theft of Public Property- Title 18, United States Code, Sections 641, 2 and 3551 et seq<br>(2)</td>
<td></td>
<td width="40%">Dismissed on deft's motion.</td>
</tr>

<tr>
<td width="40%" valign="top"><br><b><u>Highest Offense Level (Terminated)</u></b></td>
</tr>
<tr>
<td width="40%" valign="top">Felony</td>
</tr>

<tr>
<td width="40%" valign="top"><br><b><u>Complaints</u></b></td>
<td></td>
<td width="40%" valign="top"><br><b><u>Disposition</u></b></td>
</tr>

<tr>
<td width="40%"> 18 USC 1956</td>
<td></td>
<td width="60%"></td>
</tr>
</tbody></table>

Which is formatted as:
<img width="670" alt="screen shot 2018-01-09 at 18 59 12" src="https://user-images.githubusercontent.com/1270718/34749406-3effc9cc-f56f-11e7-8b07-d0d8e07aa2eb.png">

Nothing from Pending Counts to Complaints is handled by the RECAP system, and it all should be.
Honestly, there's an argument that maybe the CL docket page should provide a link to the raw underlying HTML. Perhaps one day we'll be at a point where it is all parsed, but that day might be far off. Why not let users see it?

**Comment by mlissner** [comment] 2018-01-10 07:06
> Honestly, there's an argument that maybe the CL docket page should provide a link to the raw underlying HTML. Perhaps one day we'll be at a point where it is all parsed, but that day might be far off. Why not let users see it?

That's an interesting idea. The problem is...which underlying HTML? We store every upload that we get...some may be incomplete, some may be old? Maybe we provide it all as a list for users to sort out themselves?

**Comment by brianwc** [comment] 2018-01-10 15:57
Saving all the HTML is probably unworkable. We should just start parsing
and storing this super interesting data. Criminal attorneys would probably
LOVE to be able to search by these fields.

**Comment by mlissner** [comment] 2018-01-10 17:05
Oh, we're storing all the HTML already. It's only a couple GB so far.

**Comment by johnhawkinson** [comment] 2018-01-10 17:14
Yeah, like:

> Saving all the HTML is probably unworkable.
 
Why? In what way?

> We should just start parsing and storing this super interesting data. Criminal attorneys would probably LOVE to be able to search by these fields.

Well, yes, that's the point of this Issue ;)

**Comment by johnhawkinson** [comment] 2018-01-10 17:54
> That's an interesting idea. The problem is...which underlying HTML? We store every upload that we get...some may be incomplete, some may be old? Maybe we provide it all as a list for users to sort out themselves?

I don't think this is a "problem." People who want structured data will of course look to the parsers. You could just throw up the HTML in an apache autoindex directory, just like how the IA gives PDF+xml+torrent access, e.g. http://ia800101.us.archive.org/23/items/gov.uscourts.dcd.190596/:

<img width="760" alt="screen shot 2018-01-10 at 12 53 56" src="https://user-images.githubusercontent.com/1270718/34787469-5c97c30e-f605-11e7-989a-ca8600660694.png">

Sure, you can apply more work and do better, but best is the enemy of good enough.

**Comment by mlissner** [comment] 2018-01-10 18:17
No apache index pages for our users — they're too ugly and it's easy to do better — but I think we could do similar without too much hassle. I just worry that seeing 50 version of almost the same thing will confuse people.

Another important point: We aren't redacting the receipt info that's at the bottom of every page. Nuking that before posting it is a *must* or else you could figure out which people are pulling which data.

**Comment by johnhawkinson** [comment] 2018-01-10 18:22
> No apache index pages for our users — they're too ugly and it's easy to do better

Fair enough. But I would caution you that sometimes what we  think is "better" actually… isn't. E.g. in https://github.com/freelawproject/recap/issues/195 there are halfadozen examples of things that the CL "pretty" docket page fails at that the IA docket page (not an autoindex) gets right. But several of them apply to the IA autoindex page, too.

"Good design is harder than it looks."

**Comment by mlissner** [comment] 2018-05-08 22:30
Here's how I think this data will come together once scraped. This will hang off of a party in the docket JSON information:

```
                'criminal_data': {
                    'pending_counts': 'None',
                    'highest_offense_level_opening': 'None',
                    'highest_offense_level_terminated': 'Felony',
                    'counts': [{
                        'name': 'Attempted money laundering',
                        'disposition': '',
                        'status': 'pending',
                    }, {
                        'name': 'Theft of public property',
                        'disposition': 'Dismissed on deft's motion',
                        'status': 'terminated',
                    }],
                    'complaints': [{
                        'name': '18 USC 1956',
                        'disposition': '',
                    }],
                },
```

And on the CourtListener side, I think I'll hang this data as a table off of the party table.

In the front end, I'm a little confused by PACER. It shows something like:

Pending Counts
Highest Offense Level (Opening)
Terminated Counts
Highest Offense Level (terminated)
Complaints

Seems like a better layout would be:

### Counts

Description | Status | Disposition
---- | ---- | -----
18:1326 Illegal Reentry Following Deportation | Pending | BOP 37 months followed by three yrs supervised release. Special assessment $100.00
Theft of Public Property- Title 18, United States Code, Sections 641, 2 and 3551 et seq | Terminated | Dismissed on deft's motion.

### Highest Offense Level

**Opening:** Felony
**Terminated:** None

**Complaints**: 1235: Reentry of deported alien

That seems a LOT better to me than splitting up the Counts and the offense level information. But maybe PACER did some user testing on this....

**Comment by johnhawkinson** [comment] 2018-05-08 23:08
Well, I would encourage you to not gratuitously change the format from CMECF's just because it makes more sense to you.

From the perspective of the litigants, the terminated counts don't matter anymore. The pending counts and the current highest offense level  matter, the historical ones aren't relevant for prosecuting the case or for sentencing, etc. So it makes a certain amount of sense to have the relevant stuff first and the irrelevant stuff last.

**Comment by mlissner** [comment] 2018-05-08 23:17
> Well, I would encourage you to not gratuitously change the format from CMECF's just because it makes more sense to you.

Agreed, which is why I was putting it out there how odd their design seemed.

**Comment by mlissner** [comment] 2018-05-11 04:43
The full to do for this issue is:

 - [x] Update Juriscraper to capture this information 
    Done in https://github.com/freelawproject/juriscraper/commit/9c71527442f77627d361688117b668100952bca5

 - [x] Update the CourtListener data model
    Done in https://github.com/freelawproject/courtlistener/commit/0310b474d955bc03563d8c661d875e63097532f1

 - [x] Update the front end to display the information

 - [x] Recrawl all criminal dockets to populate this information (there [are currently][crim] 338,736 Cases with 3,036,562 Documents — not too bad!)

For now I'm focused on 1-3 since search and historical data aren't a part of the current push. Hopefully the rest will come eventually.

[crim]: https://www.courtlistener.com/?q=docketnumber%3Acr&type=r&order_by=random_123+desc

**Comment by mlissner** [comment] 2018-05-15 23:10
Recrawling is underway. Should be relatively fast. Once you filter down to dockets with parties and with 'cr' in their docket number, it's not that many. Only about 41k.

    ds = Docket.objects.filter(parties__isnull=False, docket_number__icontains='cr', source__in=Docket.RECAP_SOURCES)
    for d in ds:
        print("Doing %s" % d.pk)
        d.reprocess_recap_content()

**Comment by mlissner** [comment] 2018-05-15 23:11
I'm closing this bug. The only remaining piece is to make this searchable, and I'm creating a separate issue for that.

**Closed as completed by mlissner** 2018-05-15 23:11 UTC
