### ISSUE TITLE
Downloaded file finishes downloading bytes in Firefox but never completes

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#204] opened 2017-11-15 17:00 UTC
I attempted to download a main file (Document 1) and an attachment (Document 1-1) from 3:16-cv-01675-RPC Smith v. Credit Acceptance Corporation in PAMD via the History page and neither file completed downloading in Firefox, which told me that the time remaining was unknown. I was able to save the files using the correct naming scheme pseudo-button that appears. The randomly-named files had zero bytes.
![downloads](https://user-images.githubusercontent.com/8204476/32849190-5344da6a-c9e3-11e7-8f8c-ef574c5af09e.png)

**Comment by mlissner** [comment] 2017-11-15 17:04
Sounds like trouble. Can you put your FF version in here, please? And I take it that you've got your PDF reader set to download items rather than preview them in the browser?

**Comment by mlissner** [comment] 2017-11-15 17:04
Also, if you're using FF 56, can you try on FF 57. They're pretty easy to install side by side.

**Comment by PlainSite** [comment] 2017-11-15 17:08
This is on Firefox 57 64-bit on Mac OS 10.12.6. PDFs are set to download.

**Comment by mlissner** [comment] 2017-11-15 18:26
Glad to see you got the upgrade. I'll see if I can repro it.

**Comment by mlissner** [comment] 2018-02-06 18:25
I think this was probably caused by the broken docket history reports that I fixed yesterday. I can't reproduce this now. If you can still reproduce it, please let me know, and I'll reopen. Otherwise, I'm closing this one out for the time being.

**Closed as completed by mlissner** 2018-02-06 18:25 UTC
