### ISSUE TITLE
IA feed stuck

### ISSUE THREAD

**Issue by jeffs000** [freelawproject/recap#163] opened 2016-08-09 16:10 UTC
Hello, it appears as though the IA feed is stuck, the last update was yesterday at 1300 UTC (approx): https://archive.org/advancedsearch.php?q=collection%3Ausfederalcourts&fl[]=identifier&fl[]=publicdate&sort[]=addeddate+desc&sort[]=&sort[]=&rows=1000&page=1&output=json#raw

**Comment by jeffs000** [comment] 2016-08-09 20:37
Looks like it's slowly returning to normal.

**Comment by jeffs000** [comment] 2016-08-09 22:17
Or not, seems to have stalled again.

**Comment by mlissner** [comment] 2016-08-10 18:59
An update: This is an issue with our host. We're on a shared server, and the other server is hogging all the disk IO. We're getting moved to a better server, but it's taking time. Our host, Rackspace, is horrible.

**Comment by jeffs000** [comment] 2016-08-10 20:50
What kind of server resources do you need? I'd be interested in helping out with hosting. I wouldn't think that the server would need to be too beefy.

**Comment by mlissner** [comment] 2016-08-10 20:55
We don't need much to be honest, and we have a plan to migrate the OS to our own hardware, but we haven't been able to get to that so far. This issue is particularly annoying because when you have a shared host with 2GB of RAM and a couple CPUs you don't expect that somebody else on that shared host can totally dominate the traffic, making it impossible for you to do anything. Shared hosts aren't supposed to work that way, but with Rackspace, that's the way they work.

**Comment by mlissner** [comment] 2016-08-11 22:55
I think this is resolved. Rackspace moved us to a new server that should be faster, and items seem to be flowing. Thanks for noticing the problem and filing the issue.

**Comment by jeffs000** [comment] 2016-08-12 22:46
Seems to still be happening :(

**Comment by mlissner** [comment] 2016-08-12 22:48
Yeah, Rackspace has failed to move us to a new machine. I just got off the phone with them. We're now at level 3 support. Some content has been pushed, but there's quite a backlog.

**Comment by jeffs000** [comment] 2016-08-12 23:14
I've had great experiences with Linode. I'm willing to donate a 4gigs of RAM machine with backups, if you're interested.

https://www.linode.com/pricing

**Comment by jeffs000** [comment] 2016-08-18 22:48
Just an update from what I'm seeing -- The uploads seem to restart every few hours but get stuck. The uploads restart in reverse alphabetical order but always stop when uploading docs from texas cases.

https://archive.org/advancedsearch.php?q=collection%3Ausfederalcourts&fl[]=identifier&fl[]=publicdate&sort[]=addeddate+desc&sort[]=&sort[]=&rows=1000&page=1&output=json#raw

**Comment by mlissner** [comment] 2016-08-18 22:52
Yeah, there's a strange new issue with cases that have colons in the case number that we haven't seen before. Right now, killing the upload script and then restarting it seems to fix the issue, so there's a cronjob doing that, but I haven't been able to look into why that's helping.

**Comment by jeffs000** [comment] 2016-08-18 22:53
Ok, thanks for the update.

**Comment by jeffs000** [comment] 2016-08-31 15:10
Howdy - It looks like the feed is stuck on Texas again.

**Comment by jeffs000** [comment] 2016-09-09 16:58
Bump -- the feed is still sticking on Texas.

**Comment by mlissner** [comment] 2016-09-12 18:19
This should be fixed again. I'm looking into the root cause as well. Thanks for alerting us again.

**Closed as completed by mlissner** 2016-09-12 18:19 UTC
