### ISSUE TITLE
Recap not working

### ISSUE THREAD

**Issue by nmarritz** [freelawproject/recap#150] opened 2015-11-12 16:25 UTC
**Please describe the problem you are having:**

When I log in to pacer, my "R" turns blue, indicating it's active. But when I view and save documents, nothing happens—I get no notification from the app, and the docs don't show the blue "R" next to them the next time I log in.  What gives?

**Do you use Chrome or Firefox and what version do you have installed:**

Chrome version 46.0.2490.86 m
**When did this problem first start and how long have you been putting up with it:**

About 5 months

**What PACER website were you on when this happened:**

All of them.

E.D. Wis.
E.D. Va.
E.D. Wash.

**If possible, what case number were you working on:**

E.D. Wis. 1:12-cv-209
E.D. Va.: 1:15-cv-1415
E.D. Wash.: 2:11-cv-3088

**Comment by mlissner** [comment] 2015-11-12 17:16
Thanks for the report, @nmarritz. I just did a basic test looking up E.D. Wis. 1:12-cv-209 using Chrome with the latest version of the extension. I loaded up the full docket ($3), then downloaded document 121 ($0.20), which I now see working its way through our system.

Another question: Can you tell me what version of RECAP you have installed? It's possible (though unlikely) that you have an older version. You can find this by looking in your settings. 

If that's the latest (0.8.6), our only other option is to begin debugging. To do that, we'll want to [create a new user profile](https://support.google.com/chrome/answer/142059?hl=en) and see if that solves the problem. We've seen a few cases where other extensions or settings cause conflicts. So far though, we haven't been able to identify which settings exactly were the culprit.

Let me know if this helps.

**Comment by nmarritz** [comment] 2015-11-12 17:28
Thank you for the quick reply. I've got version 0.8.6 installed, so I'm not
sure what the deal is!

**Comment by mlissner** [comment] 2015-11-12 18:18
Gotcha. If you can reproduce it in a new profile, or identify a setting that affects it, that'd be hugely valuable. Otherwise, we can't reproduce it, so it's going to be nearly impossible to fix.

(Extensions are _very_ hard to debug in general.)

**Comment by nmarritz** [comment] 2015-11-12 18:50
Understood. Tried it with a new profile—same deal. Oh well.

N.

**Comment by mlissner** [comment] 2015-11-12 19:05
The other option is to use Firefox, though I know it's about to go through some growing pains since Mozilla is changing the entire extension API. Still though, Chrome is working in general, so something is off somewhere.

**Comment by nmarritz** [comment] 2015-11-12 22:04
Yeah, maybe the security settings on my work computer? Who knows.

Anyway, now that this experiment has concluded, how do I get my old Chrome
profile back?

**Comment by mlissner** [comment] 2015-11-13 17:06
https://support.google.com/chrome/answer/2364824?hl=en should have the instructions, I believe, unless you somehow deleted your old profile. I'm going to close this ticket until we get steps to reproduce or more info.

Thanks for getting in touch though. If we can help to get things working for you, let me know.

**Closed as completed by mlissner** 2015-11-13 17:06 UTC
