### ISSUE TITLE
sendRemoveListener on closed conduit error from RECAP extension

### ISSUE THREAD

**Issue by hlieberman** [freelawproject/recap#292] opened 2020-09-11 21:58 UTC
It appears that the Firefox extension in FF Nightly, at least with the configuration that I have installed, no longer uploads cases that I purchase through PACER.

When looking at the debug console for Firefox, I see the following error attributed to the RECAP extension.  I'm not sure if it's related or not, however:

```
sendRemoveListener on closed conduit info@recapthelaw.org.274878103690 ConduitsChild.jsm:108
    _send resource://gre/modules/ConduitsChild.jsm:108
    _send self-hosted:1265
    removeListener resource://gre/modules/ExtensionChild.jsm:663
    removeListener resource://gre/modules/ExtensionChild.jsm:886
    onChanged chrome://extensions/content/child/ext-storage.js:337
    removeListener resource://gre/modules/ExtensionCommon.jsm:2517
    revoke resource://gre/modules/ExtensionCommon.jsm:2539
    close resource://gre/modules/ExtensionCommon.jsm:2544
    unload resource://gre/modules/ExtensionCommon.jsm:909
    unload resource://gre/modules/ExtensionPageChild.jsm:261
    unload resource://gre/modules/ExtensionPageChild.jsm:298
    destroyExtensionContext resource://gre/modules/ExtensionPageChild.jsm:482
    observe resource://gre/modules/ExtensionPageChild.jsm:395
```

**Do you use Chrome or Firefox and what version do you have installed:**
Firefox Nightly, currently 82.0a1 (2020-09-10) (64-bit), with RECAP Plugin 1.2.26

**When did this problem first start and how long have you been putting up with it:**
I first n```oticed it start a couple of months ago, but since I rarely use PACER, it's only now that I've stopped to debug and verify it was actually occurring.

**What PACER website were you on when this happened:**
ecf.ca3.uscourts.gov, but it appears to happen on all cases I attempt.

**If possible, what case number were you working on:**
20-1422, document 25.

**Other Installed Extensions**:

It's possible that one of my other extensions are blocking the traffic, as several of them are privacy related and do various things to network traffic.  For completeness, the extensions I have installed are:

```
Amazon.com	extension	1.3	true	amazondotcom@search.mozilla.org
Bing	extension	1.2	true	bing@search.mozilla.org
Bitwarden - Free Password Manager	extension	1.45.0	true	{446900e4-71c2-419f-a6a7-df9c091e268b}
Brief	extension	2.6.0	true	brief@mozdev.org
Cookie AutoDelete	extension	3.5.1	true	CookieAutoDelete@kennydo.com
DuckDuckGo	extension	1.1	true	ddg@search.mozilla.org
eBay	extension	1.2	true	ebay@search.mozilla.org
Firefox Multi-Account Containers	extension	7.0.2	true	@testpilot-containers
Google	extension	1.1	true	google@search.mozilla.org
HTTPS Everywhere	extension	2020.8.13	true	https-everywhere@eff.org
RECAP	extension	1.2.26	true	info@recapthelaw.org
uBlock Origin	extension	1.29.2	true	uBlock0@raymondhill.net
Wikipedia (en)	extension	1.1	true	wikipedia@search.mozilla.org
```

**Comment by johnhawkinson** [comment] 2020-09-11 22:04
RECAP support for Appellate Courts is somewhat of a work in progress.
You should not expect document uploads to work for appellate cases right now, although hopefully that will change soon.
If you have the chance to test on a district court (or bankruptcy court) filing, RECAP should work as expected.

On the other hand, the "sendRemoveListener on closed conduit" shouldn't be happening either?
Not sure about that one.

**Comment by hlieberman** [comment] 2020-09-11 22:08
Aha -- indeed, it does work correctly when I try it with a district court case.

Is there anything useful I can do to debug the closed conduit error?  I haven't seen any misbehavior happening concurrently with it, so it's possible it's just a spurious error.

**Comment by mlissner** [comment] 2020-09-11 22:49
I think we'll have a fresh rewrite of the appellate code pretty soon, so I think it's probably not worth digging too much into this error unless we can make it happen on the new branch. If you want to test that out, I can track down where the ~dev~ *branch* for that is.

**Comment by mlissner** [comment] 2022-12-02 23:44
This appears to be related to appellate. Flagging for you, @ERosendo.

**Comment by mlissner** [comment] 2022-12-02 23:45
It's worth making sure this bug doesn't come up again once your appellate work lands. I suspect this bug is irrelevant though, so if it isn't going to be an issue, we can just close it.

**Comment by ERosendo** [comment] 2023-01-06 01:48
@mlissner I uploaded document 25 and 169 from docket [20-1422](https://www.courtlistener.com/docket/59768798/united-states-v-safehouse/)  using the latest code for the extension and **Firefox version 108.0.2 (64-bit)**, but I was not able to reproduce the error.

I also installed the following extensions (trying to replicate @hlieberman list of installed extensions):

| Name  | Version | ID |
| ------------- | ------------- | ------------- |
| Amazon.com  | 1.4  | amazondotcom@search.mozilla.org|
| Bing  | 1.4 | bing@search.mozilla.org|
| Bitwarden - Free Password Manager | 	2022.12.1 | {446900e4-71c2-419f-a6a7-df9c091e268b} |
|  Brief	| 	2.6.1	| 	brief@mozdev.org| 
| Cookie AutoDelete | 3.8.2 |  CookieAutoDelete@kennydo.com | 
| DuckDuckGo	| 1.2	| 	ddg@search.mozilla.org| 
| eBay	| 	1.4	| 	ebay@search.mozilla.org| 
| Firefox Multi-Account Containers	| 8.0.9 | @testpilot-containers | 
|uBlock Origin | 1.46.0 |	uBlock0@raymondhill.net |
|Wikipedia (en) | 1.2 | wikipedia@search.mozilla.org |

**Comment by mlissner** [comment] 2023-01-06 02:46
Cool. Closing.

**Closed as not planned** 2023-01-06 02:46 UTC
