### ISSUE TITLE
Docket weirdness

### ISSUE THREAD

**Issue by PlainSite** [freelawproject/recap#149] opened 2015-10-29 03:38 UTC
This docket only has 174+ entries on PACER, but on RECAP it goes to 400+, with the dates backtracking in the middle. Were two cases combined?

http://ia802506.us.archive.org/22/items/gov.uscourts.utb.344830/gov.uscourts.utb.344830.docket.html

**Comment by mlissner** [comment] 2015-10-29 16:23
Yeah, this looks very weird. There's an issue I've seen once before where multiple dockets get somehow merged. I think it's actually a bug in the extensions, that actually gets the metadata from one docket mixed up with that of another.

I'll take a look at this when I have a moment, but there's not a ton that I'll be able to do short of deleting the docket, until we can identify how the problem is being created. We really need steps to reproduce.

**Comment by PlainSite** [comment] 2015-11-03 23:01
This one is corrupt as well:

http://archive.org/download/gov.uscourts.nhb.80775/

Can we remove it from the Internet Archive so it can get re-cached properly? Mr. D------- is understandably not too happy.

**Comment by mlissner** [comment] 2015-11-03 23:16
Both dockets are deleted.

**Closed as completed by mlissner** 2015-11-03 23:16 UTC
