### ISSUE TITLE
Docket Data Missing

### ISSUE THREAD

**Issue by danieldjewell** [freelawproject/recap#267] opened 2019-02-14 05:39 UTC
It appears that a docket's data has gone missing ... it also does not appear on the search. 

https://www.courtlistener.com/docket/6358216/united-states-v-lacey/ 
United States v. Lacey (2018 D. Ariz - 2:18-cr-00422) 

I am 100% certain there were archived documents from this case in the RECAP docket in the past. However, they appear to be completely gone. (My inner programmer thinks of database maintenance and/or some kind of batch process gone awry that could be affecting other dockets.) 

This is the only one that I've seen with this issue -- however, it's entirely possible that there are other dockets affected. 

(Given the FLP's clear notice of takedown -- if that was done in this case, it seems that an appropriate action would be to post the court order indicating the removal - not sure if that's what happened here but I thought I'd mention it)

And many kudos to everyone for everything that you do!

**Comment by mlissner** [comment] 2019-02-14 18:20
Is it possible that you were looking at a different URL with those docs? We have a bug in criminal cases that creates multiple pages for the same case. The bug is in our data model since we assumed each case only has one internal case ID in PACER, but turns out that's not true....

See here for other URLs: https://www.courtlistener.com/?q=&type=r&order_by=score+desc&case_name=United+States+v.+Lacey&docket_number=2%3A18-cr-00422

**Comment by danieldjewell** [comment] 2019-02-18 14:46
Thanks for the response! I'm 99.9% certain no, I wasn't using a different URL -- I couldn't find the docket for that case using search (which I found strange),  so I dug through my history to find that URL. 

That said, I do see what you're saying about the search and how the dockets appear. I guess what's interesting is that the search URL you mentioned shows 8 different dockets for the same case. (I'll have to go back and gather more info on internals to fully understand what's going on.) 

I guess the question becomes: If PACER shows just 1 docket for the case what is causing 8 to appear on RECAP? In the various dockets provided by that search, some docket entries are duplicated, some are unique. In any event, one of the key maxims for data is being broken: "One source of the truth (the data)". 

Even if PACER shows multiple dockets, it seems wise to correlate the data in RECAP in order to provide a better view. 

Ideas: 

- Summary view of the case -- show all results that match the same Case # and Court (and put a link to this display on all related cases)
- Concatenate the related entries into a single page (the existing data structure could be preserved) - if duplicate docket entries exist in the sub-entries, show them as such (or compare them by PACER access URL or content to determine if they are the same or different)

**Comment by mlissner** [comment] 2019-02-18 23:18
Here's the longer discussion of the issue: https://github.com/freelawproject/courtlistener/issues/2185. I *think* this issue might be a duplicate of it, but that depends on whether the 0.1% chance that you were looking at different URLs is true.

**Comment by mlissner** [comment] 2019-09-06 00:52
Closing for lack of reproduce case.

**Closed as completed by mlissner** 2019-09-06 00:52 UTC
