### ISSUE TITLE
Nebraska Bankruptcy dockets not being abbreviated correctly -"nebraskab"

### ISSUE THREAD

**Issue by jeffvianet** [freelawproject/recap#164] opened 2017-03-17 21:22 UTC
See, e.g., gov.uscourts.nebraskab.93078.

**Comment by mlissner** [comment] 2017-03-17 21:24
Not sure what you mean, @jeffvianet. Can you please post more details and a link if that makes sense?

**Comment by jeffvianet** [comment] 2017-03-17 21:29
Traditionally the abbreviation for that court has been "neb" and it's showing up in cases as "nebraskab," at least it has started to show up that way today (from what I've noticed). 

Old abbreviation: https://ia600501.us.archive.org/32/items/gov.uscourts.neb.158026/

New abbreviation: https://ia601508.us.archive.org/30/items/gov.uscourts.nebraskab.93078

**Comment by mlissner** [comment] 2017-03-17 21:36
Gotcha. Yes, this is by design and it happening as we move towards CourtListener being the main host for RECAP content. `nebraskab` is the CourtListener abbreviation for that court. 

Hopefully this won't cause too many issues, but the big picture here is that IA is becoming secondary storage (slowly but surely) and CourtListener is becoming primary. We badly need to do this to simplify our architecture and (I think) moving everything towards the CourtListener standards should be the right way forward.

For the most part, the two systems (RECAP and CourtListener) use the same IDs, but some of them do differ, like this one. (Mostly, this was for technical reasons, though I fully admit that I forget why we didn't use neb for this back in the day. I do remember that using `del` for Delaware was an issue because `del` is a keyword in Python.) In any case, if you need help mapping between the two, we should be able to provide some code for that. It's relatively straightforward, I believe.

Closing for now (since it's by design), but feel free to re-open if you want to make the case for this change not happening.

**Closed as completed by mlissner** 2017-03-17 21:36 UTC

**Comment by jeffvianet** [comment] 2017-03-17 21:42
Ah, I didn't realize that there was a transition in process. Is there any API available for CourtListener so I don't have to rely on the IA feed?

**Comment by mlissner** [comment] 2017-03-17 21:47
That's coming. Right now I'm working on adding all of the free opinions that are in PACER. Once those are added, the API is up next. It should be fairly fast to put together, but there may be some frustrating performance issues to deal with that slow things down. Either way, IA will continue working ± this change, for a good while yet. 

By the way, the only content that's coming from this change (at this point) is the free opinions that we're about to download.

**Comment by jeffvianet** [comment] 2017-03-17 21:48
Ok, good to know. Will the free content also synchronize with the IA?

**Comment by jeffvianet** [comment] 2017-03-17 21:50
And yes, please let me know the location of the code for mapping the new court abbreviations.

**Comment by mlissner** [comment] 2017-03-17 22:20
The `nebraskab` that you're seeing is the beginning of the synchronization. You can expect millions more documents over the next couple weeks.

Here's the code for the mapping, though you'll see it's not on the master branch yet: 

https://github.com/freelawproject/courtlistener/blob/879c34cf0c52ea767a3179c67b2b29771460e9c8/cl/lib/pacer.py#L35-L56

Still, it should give you some  idea of what it's looking like.
